config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'

  get    'signup', to: 'users#new'
  get    'login' , to: 'sessions#new'
  post   'login' , to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :users do
    member do
      get :followings, :followers, :favorites
    end
  end
  
  resources :microposts do
    member do
      post :retweet
    end
    resource :favorites, only: [:create, :destroy]
  end
  
  resources :relationships, only: [:create, :destroy]

end

app/models/user.rb
class User < ActiveRecord::Base

  # コールバック
  # メールアドレスのアルファベットを小文字に
  before_save { self.email = self.email.downcase }

  # nameは必須かつ最大文字数は50文字
  validates :name, presence: true, length: { maximum: 50 }

  # 正規表現パターン
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  # emailは必須かつ255文字以内でVALID_EMAIL_REGEXに一致しユニークであること
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  # データベースに安全にハッシュ化（暗号化）されたpassword_digestを保存する
  # passwordとpassword_confirmationをモデルに追加して、パスワードの確認が一致するか検証する
  # パスワードが正しいときに、ユーザーを返すauthenticateメソッドを提供する
  has_secure_password

  # 更新時のみ有効：profileが入力されていた場合、300文字以内であること
  validates :profile, absence: true, 
                      on: :create
  validates :profile, allow_blank: true, length: { maximum: 300 },
                      on: :update

  # 更新時のみ有効：areaが入力されていた場合、30文字以内であること
  validates :area, absence: true, 
                   on: :create
  validates :area, allow_blank: true, length: { maximum: 30 },
                   on: :update

  # それぞれのユーザーは複数の投稿を持つことができる
  has_many :microposts

  # ユーザーがフォローしているアカウントを取得（フォロー）
  has_many :following_relationships, class_name:  "Relationship",
                                     foreign_key: "follower_id",
                                     dependent:   :destroy
  has_many :following_users, through: :following_relationships, source: :followed

  # ユーザーをフォローしているアカウントを取得（フォロワー）
  has_many :follower_relationships, class_name:  "Relationship",
                                    foreign_key: "followed_id",
                                    dependent:   :destroy
  has_many :follower_users, through: :follower_relationships, source: :follower


  # 他のユーザーをフォローする
  def follow(other_user)
    following_relationships.find_or_create_by(followed_id: other_user.id)
  end

  # フォローしているユーザーをアンフォローする
  def unfollow(other_user)
    following_relationship = following_relationships.find_by(followed_id: other_user.id)
    following_relationship.destroy if following_relationship
  end

  # あるユーザーをフォローしているかどうか？
  def following?(other_user)
    following_users.include?(other_user)
  end

  # 自分とフォローしているユーザーのつぶやきを取得する
  def feed_items
    Micropost.where(user_id: following_user_ids + [self.id])
  end

  # お気に入りツイートを取得する
  has_many :favorites, foreign_key: 'user_id', dependent: :destroy
  has_many :favorite_microposts, through: :favorites, source: :micropost

  # お気に入り登録する
  def favorite(micropost)
      favorites.find_or_create_by(micropost_id: micropost.id)
  end
    
  # お気に入り解除する
  def unfavorite(micropost)
      favorite = favorites.find_by(micropost_id: micropost.id)
      favorite.destroy if favorite
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_params, only: [:show, :edit, :update, :followings, :followers, :favorites]
  before_action :correct_user, only: [:edit, :update]

  def show
    @title = 'Micropost'
    @count = @user.microposts.count
    @user = User.find(params[:id])
    @microposts = @user.microposts.order(created_at: :desc).page(params[:page])
  end
  
  def new
    # インスタンス生成
    @user = User.new
  end

  # アカウント作成
  def create
    @user = User.new(user_params)
    if @user.save
      # フラッシュメッセージ表示
      flash[:success] = "Welcome to the Sample App!"
      # 新規登録後、ユーザー詳細ページへリダイレクト
      redirect_to @user
    else
      render 'new'
    end
  end

  # アカウント編集
  def edit
  end

  # アカウント更新
  def update
    # ユーザー情報更新（ハッシュごと）
    if @user.update_attributes(user_params)
      # 保存に成功した場合はshowへリダイレクト
      flash[:success] = "Update your profile."
      redirect_to @user
    else
      # 保存に失敗した場合は編集画面へ戻す
      render 'edit'
    end
  end
  
  # フォロー一覧取得
  def followings
    @title = "Follow users"
    followings = @user.following_users
    @count = followings.count
    @users = followings.page(params[:page])
    render 'show_follow'
  end

  # フォロワー一覧取得
  def followers
    @title = "Followers"
    followers = @user.follower_users
    @count = followers.count
    @users = followers.page(params[:page])
    render 'show_follow'
  end

  # お気に入り登録
  def favorites
    @title = 'Favorites'
    @count = @user.favorite_microposts.count
    @microposts = @user.favorite_microposts.page(params[:page])
    render 'show'
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation,
                                 :profile, :area)
  end

  # ユーザー情報取得
  def set_params
    @user = User.find(params[:id])
  end

  # リジェクト処理
  def correct_user
    redirect_to root_path if !current_user?(@user)
  end
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

end

app/views/users/_follow.html.erb
<%= form_for(current_user.following_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% if current_user != @user %>
  <div id="follow_form">
    <% if current_user.following?(@user) %>
      <%= render 'unfollow' %>
    <% else %>
      <%= render 'follow' %>
    <% end %>
  </div>
<% end %>

app/views/users/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= render 'form_edit', f: f %>

      <%= f.submit message, class: "btn btn-primary" %>
    <% end %>

  </div>
</div>

app/views/users/_form_edit.html.erb
<% if params[:action] == 'edit' || params[:action] == 'update' %>

  <%= f.label :area %>
  <%= f.text_field :area, class: 'form-control' %>

  <%= f.label :profile %>
  <%= f.text_area :profile, class: 'form-control' %>
  
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.following_relationships.find_by(followed_id: @user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/_user.html.erb
<li id="user-<%= user.id %>">
  <%= link_to gravatar_for(user, size: 50), user %>
  <span class="user"><%= link_to user.name, user %></span>
</li>

app/views/users/_user_info.html.erb
<section class="user_info">
  <h1>
    <%= gravatar_for @user %>
    <%= @user.name %>
  </h1>
</section>

<% if current_user?(@user) %>
  <h4><%= content_tag :span, 'e-mail', class: 'label label-info' %></h4>
  <p><%= @user.email %></p>
<% end %>

<% if @user.area.present? %>
  <h4><%= content_tag :span, 'area', class: 'label label-info' %></h4>
  <p><%= @user.area %></p>
<% end %>

<% if @user.profile.present? %>
  <h4><%= content_tag :span, 'profile', class: 'label label-info' %></h4>
  <%= simple_format @user.profile %>
<% end %>
    
<p><%= link_to "user_page", @user %> | 
   <%= link_to "followings", followings_user_path(@user) %> | 
   <%= link_to "followers", followers_user_path(@user) %> | 
   <%= link_to "favorites", favorites_user_path(@user) %>
</p>

app/views/users/edit.html.erb
<h1>Profile update</h1>

<%= render 'form', message: 'Profile save' %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= render 'form', message: 'Create my account' %>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-md-4">
    <%= render 'user_info' %>
  </aside>

  <div class="col-md-8">
    <%= render 'follow_form' if logged_in? %>
    <% if @user.microposts.any? %>
      <h3><%= @title %> (<%= @count %>)</h3>
      <ol class="microposts">
        <%= page_entries_info @microposts %>
        <%= render @microposts %>
        <%= paginate @microposts %>
      </ol>
    <% end %>
  </div>
</div>

app/views/users/show_follow.html.erb
<div class="row">
  <aside class="col-md-4">
    <%= render 'user_info' %>
  </aside>

  <div class="col-md-8">
    <%= render 'follow_form' if logged_in? %>
    <h3><%= @title %> (<%= @count %>)</h3>
    <ol class="users">
      <%= page_entries_info @users %>
      <%= render @users %>
      <%= paginate @users %>
    </ol>
  </div>
</div>