config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'

  get    'signup', to: 'users#new'
  get    'login' , to: 'sessions#new'
  post   'login' , to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :users do
    member do
      get :followings, :followers, :favorites
    end
  end
  
  resources :microposts do
    member do
      post :retweet
    end
    resource :favorites, only: [:create, :destroy]
  end
  
  resources :relationships, only: [:create, :destroy]

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  mount_uploader :image, ImageUploader

  # それぞれの投稿は特定の1人のユーザーのものである
  belongs_to :user

  # user_idが存在する
  validates :user_id, presence: true
  # contentが存在し、文字数は140
  validates :content, presence: true, length: { maximum: 140 }

  # 
  has_many :favorites, foreign_key: 'micropost_id', dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  
  def favorite?(user)
    favorite_users.include?(user)
  end

end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :logged_in_user, only: [:create]

  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = "Micropost created!"
      redirect_to root_url
    else
      @feed_items = current_user.feed_items.includes(:user).order(created_at: :desc).page(params[:page])
      render 'static_pages/home'
    end
  end

  def destroy
    @micropost = current_user.microposts.find_by(id: params[:id])
    return redirect_to root_url if @micropost.nil?
    @micropost.destroy
    flash[:success] = "Micropost deleted"
    redirect_to request.referrer || root_url
  end

  # リツイート機能
  def retweet
    original = Micropost.find(params[:id])
    retweet = current_user.microposts.build(original: original.id)
    retweet.content = "＃ #{original.user.name}さんのリツイート　\n #{original.content}"
    retweet.original_image = original.image
    if retweet.save
      flash[:success] = "リツイートしました"
      redirect_to current_user
    else
      redirect_to :back
    end
  end

  private
  def micropost_params
    params.require(:micropost).permit(:content, :image, :original_image)
  end
end

app/views/microposts/_favorite.html.erb
<%= link_to "favorite", micropost_favorites_path(micropost),
                        method: :post, remote: true %>

app/views/microposts/_favorite_form.html.erb
<span id="favorite_form-<%= micropost.id %>">
  <% if micropost.favorite?(current_user) %>
    <%= render 'microposts/unfavorite', micropost: micropost %>
  <% else %>
    <%= render 'microposts/favorite', micropost: micropost %>
  <% end %>
</span>

app/views/microposts/_image.html.erb
<% if micropost.original_image.present? %>
  <%= image_tag(micropost.original_image) %>
<% elsif micropost.image.present? %>
  <%= image_tag(micropost.image.url) %>
<% end %>

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
  <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
  <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
  <span class="content"><%= simple_format micropost.content %></span>
  <span class="image"><%= render 'microposts/image', micropost: micropost %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
    <% if current_user == micropost.user %>
      <%= link_to "delete", micropost, method: :delete,
                                       data: { config: "You sure?" } %> | 
    <% end %>
    <%= render 'microposts/retweet', micropost: micropost %> | 
    <%= render 'microposts/favorite_form', micropost: micropost %>
  </span>
</li>

app/views/microposts/_retweet.html.erb
<% if micropost.original.nil? %>
  <%= link_to "retweet", retweet_micropost_path(micropost), method: :post,
                                                            data: { config: "Retweet?" } %>
<% else %>
  RT済
<% end %>

app/views/microposts/_unfavorite.html.erb
<%= link_to "unfavorite", micropost_favorites_path(micropost),
                          method: :delete, remote: true %>